#pragma once

#include <cstdint>

enum class DspModuleType : uint8_t
{
    BYPASS = 0,
    WAVESHAPER_DISTORTION,
    MICROPITCH_CHORUS,
    MULTI_MODE_FILTER,
    PITCH_SHIFTER_GRANULAR,
    ENVELOPE_VCA_COMPRESSOR,
    GLITCH_STUTTER,
    DIFFUSED_DELAY_NETWORK,
    MATHEMATICAL_WAVEFOLDER,
    FORMANT_VOCAL_SHIFTER,
    TAPE_STOP_REVERSE_ECHO,
    SIMPLE_DELAY,
    PLATE_REVERB,
    RHYTHM_GATE,
    GRANULAR_DELAY,
    COMB_RESONATOR,
    SPECTRAL_FREEZE,
    FREQ_SHIFTER,
    REVERSE_BUFFER,
    GRAIN_SCRUBBER,
    SPECTRAL_FILTER,
    CONVOLUTION_SPACE,
    RANDOM_MODULATOR,
    RESAMPLE_BITCRUSH,
    TREMOLO,
    FLANGER,
    ANALOG_OCTAVER
};
